name: Update Protos

on:
  workflow_dispatch:
  schedule:
   - cron: '35 3 * * *'

jobs:
  unit_tests:
    name: Update Protos
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: ['ros:iron', 'ros:rolling']
    container: ${{ matrix.container }}


    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build protos
      run: ./build_protos.bash
    - name: Set ownership
      run: |
        # this is to fix GIT not liking owner of the checkout dir
        chown -R $(id -u):$(id -g) $PWD
    - name: Commit protos
      run: ./commit_protos.bash
 